### ISSUE TITLE
Rename species to taxon and make it a required field

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#83]
As a result of an early meeting, we implemented the observations with the option to have no species set. However, that is a case that we don't catch on other places (the home page cannot handle that right now and the sync push might also complain).
Are we actually really sure that we want to allow this?

An alternative was also proposed during a later meeting when discussing the species selector (with images from the different species): there we would have a final option "I don't know" in which case the species would be set to "Insect".

If we all agree on this option, we should make the species required on the database level to prevent issues on other places in the app.

**Comment by peterdesmet** [comment]
I’m fine making it required (assuming
higher taxa up to kingdom can be set). Pinging @karelschoonvaere @timadriaens.

**Comment by bartaelterman** [comment]
@niconoe I'm having some issues here: The model is imported in the migrations files so those break if I rename it. I know there are ways to do it, but I'm not sure how anymore. I think it's better if you have a look.

**Comment by niconoe** [comment]
Done!

(but I'll have a second look because that's the kind of change that break stuff - please also report issues).

**Comment by bartaelterman** [comment]
Hey @niconoe I get an error when I run the migrations:

```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, page_fragments, sessions, vespawatch
Running migrations:
  Applying vespawatch.0005_auto_20181126_1359... OK
  Applying vespawatch.0006_auto_20181126_1416...Traceback (most recent call last):
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column vespawatch_taxon.identification_picture_individual does not exist
LINE 1: ... "vespawatch_taxon"."inaturalist_pull_taxon_ids", "vespawatc...
                                                             ^
```

I  can try to drop the database entirely, but others might run into this as well. I'm not sure what could be the cause

**Comment by niconoe** [comment]
Aw, that's strange, I didn't had this one... no forgotten/unapplied migrations? It may be simplest to drop and recreate... Tell me how it goes!

**Comment by bartaelterman** [comment]
hey @niconoe , I droppend and recreated the database, but I still have the same issue.

**Comment by bartaelterman** [comment]
Here's the full traceback

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 523, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 627, in _alter_field
    new_default = self.effective_default(new_field)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 218, in effective_default
    default = field.get_default()
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/fields/related.py", line 926, in get_default
    field_default = super().get_default()
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 798, in get_default
    return self._get_default()
  File "/Users/bartaelterman/Projects/INBO/VespaWatch/vespa-watch/vespawatch/models.py", line 231, in get_default_taxon_id
    return Taxon.objects.filter(name='Vespa velutina').first().pk
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/query.py", line 605, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/bartaelterman/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column vespawatch_taxon.identification_picture_individual does not exist
LINE 1: ... "vespawatch_taxon"."inaturalist_pull_taxon_ids", "vespawatc...
```

**Comment by bartaelterman** [comment]
I'm assuming it's migration `0006` causing the issue. It imports `get_default_taxon_id` which uses the `Taxon` model that has a `identification_picture_individual` field defined, but at that point in the migration, that field is still called `identification_picture`.

**Comment by bartaelterman** [comment]
A good time to squash all migration files one more time?

**Comment by niconoe** [comment]
Done, should be better now! @peterdesmet @bartaelterman @stijnvanhoey : You'll need to drop/recreate database one more time, sorry for the inconvenience.

**Comment by bartaelterman** [comment]
looks good to me now!
